PROG = pacman

MAN = pacman.8

SRCS = \
	conf.c \
	database.c \
	deptest.c \
	package.c \
	pacman.c \
	query.c \
	remove.c \
	sync.c \
	callback.c \
	upgrade.c \
	util.c

.include "../Makefile.incl"

.include <bsd.prog.mk>
